// Auto-generated. Do not edit!

// (in-package cpp.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class LoopClosureGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.imagepath = null;
    }
    else {
      if (initObj.hasOwnProperty('imagepath')) {
        this.imagepath = initObj.imagepath
      }
      else {
        this.imagepath = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type LoopClosureGoal
    // Serialize message field [imagepath]
    bufferOffset = _serializer.string(obj.imagepath, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type LoopClosureGoal
    let len;
    let data = new LoopClosureGoal(null);
    // Deserialize message field [imagepath]
    data.imagepath = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += _getByteLength(object.imagepath);
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'cpp/LoopClosureGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'bc491c80e6e5522eb310dc6a0d6adc73';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    string imagepath
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new LoopClosureGoal(null);
    if (msg.imagepath !== undefined) {
      resolved.imagepath = msg.imagepath;
    }
    else {
      resolved.imagepath = ''
    }

    return resolved;
    }
};

module.exports = LoopClosureGoal;
