// Generated by gencpp from file custom_srv/newResponse.msg
// DO NOT EDIT!


#ifndef CUSTOM_SRV_MESSAGE_NEWRESPONSE_H
#define CUSTOM_SRV_MESSAGE_NEWRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_srv
{
template <class ContainerAllocator>
struct newResponse_
{
  typedef newResponse_<ContainerAllocator> Type;

  newResponse_()
    : fullname()  {
    }
  newResponse_(const ContainerAllocator& _alloc)
    : fullname(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _fullname_type;
  _fullname_type fullname;





  typedef boost::shared_ptr< ::custom_srv::newResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_srv::newResponse_<ContainerAllocator> const> ConstPtr;

}; // struct newResponse_

typedef ::custom_srv::newResponse_<std::allocator<void> > newResponse;

typedef boost::shared_ptr< ::custom_srv::newResponse > newResponsePtr;
typedef boost::shared_ptr< ::custom_srv::newResponse const> newResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_srv::newResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_srv::newResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_srv::newResponse_<ContainerAllocator1> & lhs, const ::custom_srv::newResponse_<ContainerAllocator2> & rhs)
{
  return lhs.fullname == rhs.fullname;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_srv::newResponse_<ContainerAllocator1> & lhs, const ::custom_srv::newResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_srv

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_srv::newResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_srv::newResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_srv::newResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_srv::newResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_srv::newResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_srv::newResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_srv::newResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4b3ec2b8015eb1b3aac2c2800e66d332";
  }

  static const char* value(const ::custom_srv::newResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4b3ec2b8015eb1b3ULL;
  static const uint64_t static_value2 = 0xaac2c2800e66d332ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_srv::newResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_srv/newResponse";
  }

  static const char* value(const ::custom_srv::newResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_srv::newResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string fullname\n"
"\n"
;
  }

  static const char* value(const ::custom_srv::newResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_srv::newResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fullname);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct newResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_srv::newResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_srv::newResponse_<ContainerAllocator>& v)
  {
    s << indent << "fullname: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.fullname);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_SRV_MESSAGE_NEWRESPONSE_H
