// Generated by gencpp from file basicros/AddTwoPoints.msg
// DO NOT EDIT!


#ifndef BASICROS_MESSAGE_ADDTWOPOINTS_H
#define BASICROS_MESSAGE_ADDTWOPOINTS_H

#include <ros/service_traits.h>


#include <basicros/AddTwoPointsRequest.h>
#include <basicros/AddTwoPointsResponse.h>


namespace basicros
{

struct AddTwoPoints
{

typedef AddTwoPointsRequest Request;
typedef AddTwoPointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoPoints
} // namespace basicros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::basicros::AddTwoPoints > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::basicros::AddTwoPoints&) { return value(); }
};

template<>
struct DataType< ::basicros::AddTwoPoints > {
  static const char* value()
  {
    return "basicros/AddTwoPoints";
  }

  static const char* value(const ::basicros::AddTwoPoints&) { return value(); }
};


// service_traits::MD5Sum< ::basicros::AddTwoPointsRequest> should match
// service_traits::MD5Sum< ::basicros::AddTwoPoints >
template<>
struct MD5Sum< ::basicros::AddTwoPointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::basicros::AddTwoPoints >::value();
  }
  static const char* value(const ::basicros::AddTwoPointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::basicros::AddTwoPointsRequest> should match
// service_traits::DataType< ::basicros::AddTwoPoints >
template<>
struct DataType< ::basicros::AddTwoPointsRequest>
{
  static const char* value()
  {
    return DataType< ::basicros::AddTwoPoints >::value();
  }
  static const char* value(const ::basicros::AddTwoPointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::basicros::AddTwoPointsResponse> should match
// service_traits::MD5Sum< ::basicros::AddTwoPoints >
template<>
struct MD5Sum< ::basicros::AddTwoPointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::basicros::AddTwoPoints >::value();
  }
  static const char* value(const ::basicros::AddTwoPointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::basicros::AddTwoPointsResponse> should match
// service_traits::DataType< ::basicros::AddTwoPoints >
template<>
struct DataType< ::basicros::AddTwoPointsResponse>
{
  static const char* value()
  {
    return DataType< ::basicros::AddTwoPoints >::value();
  }
  static const char* value(const ::basicros::AddTwoPointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BASICROS_MESSAGE_ADDTWOPOINTS_H
