// Generated by gencpp from file basicros/AddTwoPointsResponse.msg
// DO NOT EDIT!


#ifndef BASICROS_MESSAGE_ADDTWOPOINTSRESPONSE_H
#define BASICROS_MESSAGE_ADDTWOPOINTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace basicros
{
template <class ContainerAllocator>
struct AddTwoPointsResponse_
{
  typedef AddTwoPointsResponse_<ContainerAllocator> Type;

  AddTwoPointsResponse_()
    : sum(0)  {
    }
  AddTwoPointsResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int64_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::basicros::AddTwoPointsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::basicros::AddTwoPointsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddTwoPointsResponse_

typedef ::basicros::AddTwoPointsResponse_<std::allocator<void> > AddTwoPointsResponse;

typedef boost::shared_ptr< ::basicros::AddTwoPointsResponse > AddTwoPointsResponsePtr;
typedef boost::shared_ptr< ::basicros::AddTwoPointsResponse const> AddTwoPointsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::basicros::AddTwoPointsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::basicros::AddTwoPointsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::basicros::AddTwoPointsResponse_<ContainerAllocator1> & lhs, const ::basicros::AddTwoPointsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::basicros::AddTwoPointsResponse_<ContainerAllocator1> & lhs, const ::basicros::AddTwoPointsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace basicros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::basicros::AddTwoPointsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::basicros::AddTwoPointsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::basicros::AddTwoPointsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::basicros::AddTwoPointsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::basicros::AddTwoPointsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::basicros::AddTwoPointsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::basicros::AddTwoPointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b88405221c77b1878a3cbbfff53428d7";
  }

  static const char* value(const ::basicros::AddTwoPointsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb88405221c77b187ULL;
  static const uint64_t static_value2 = 0x8a3cbbfff53428d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::basicros::AddTwoPointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "basicros/AddTwoPointsResponse";
  }

  static const char* value(const ::basicros::AddTwoPointsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::basicros::AddTwoPointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 sum\n"
;
  }

  static const char* value(const ::basicros::AddTwoPointsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::basicros::AddTwoPointsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddTwoPointsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::basicros::AddTwoPointsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::basicros::AddTwoPointsResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASICROS_MESSAGE_ADDTWOPOINTSRESPONSE_H
