// Generated by gencpp from file cpp/AddThreeInts.msg
// DO NOT EDIT!


#ifndef CPP_MESSAGE_ADDTHREEINTS_H
#define CPP_MESSAGE_ADDTHREEINTS_H

#include <ros/service_traits.h>


#include <cpp/AddThreeIntsRequest.h>
#include <cpp/AddThreeIntsResponse.h>


namespace cpp
{

struct AddThreeInts
{

typedef AddThreeIntsRequest Request;
typedef AddThreeIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddThreeInts
} // namespace cpp


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cpp::AddThreeInts > {
  static const char* value()
  {
    return "eccb72520f9288ba7471164786064905";
  }

  static const char* value(const ::cpp::AddThreeInts&) { return value(); }
};

template<>
struct DataType< ::cpp::AddThreeInts > {
  static const char* value()
  {
    return "cpp/AddThreeInts";
  }

  static const char* value(const ::cpp::AddThreeInts&) { return value(); }
};


// service_traits::MD5Sum< ::cpp::AddThreeIntsRequest> should match
// service_traits::MD5Sum< ::cpp::AddThreeInts >
template<>
struct MD5Sum< ::cpp::AddThreeIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cpp::AddThreeInts >::value();
  }
  static const char* value(const ::cpp::AddThreeIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cpp::AddThreeIntsRequest> should match
// service_traits::DataType< ::cpp::AddThreeInts >
template<>
struct DataType< ::cpp::AddThreeIntsRequest>
{
  static const char* value()
  {
    return DataType< ::cpp::AddThreeInts >::value();
  }
  static const char* value(const ::cpp::AddThreeIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cpp::AddThreeIntsResponse> should match
// service_traits::MD5Sum< ::cpp::AddThreeInts >
template<>
struct MD5Sum< ::cpp::AddThreeIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cpp::AddThreeInts >::value();
  }
  static const char* value(const ::cpp::AddThreeIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cpp::AddThreeIntsResponse> should match
// service_traits::DataType< ::cpp::AddThreeInts >
template<>
struct DataType< ::cpp::AddThreeIntsResponse>
{
  static const char* value()
  {
    return DataType< ::cpp::AddThreeInts >::value();
  }
  static const char* value(const ::cpp::AddThreeIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CPP_MESSAGE_ADDTHREEINTS_H
