// Generated by gencpp from file cpp/AddThreeIntsResponse.msg
// DO NOT EDIT!


#ifndef CPP_MESSAGE_ADDTHREEINTSRESPONSE_H
#define CPP_MESSAGE_ADDTHREEINTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cpp
{
template <class ContainerAllocator>
struct AddThreeIntsResponse_
{
  typedef AddThreeIntsResponse_<ContainerAllocator> Type;

  AddThreeIntsResponse_()
    : result(0)  {
    }
  AddThreeIntsResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int64_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::cpp::AddThreeIntsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cpp::AddThreeIntsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddThreeIntsResponse_

typedef ::cpp::AddThreeIntsResponse_<std::allocator<void> > AddThreeIntsResponse;

typedef boost::shared_ptr< ::cpp::AddThreeIntsResponse > AddThreeIntsResponsePtr;
typedef boost::shared_ptr< ::cpp::AddThreeIntsResponse const> AddThreeIntsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cpp::AddThreeIntsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cpp::AddThreeIntsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cpp::AddThreeIntsResponse_<ContainerAllocator1> & lhs, const ::cpp::AddThreeIntsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cpp::AddThreeIntsResponse_<ContainerAllocator1> & lhs, const ::cpp::AddThreeIntsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cpp

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cpp::AddThreeIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cpp::AddThreeIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cpp::AddThreeIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cpp::AddThreeIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpp::AddThreeIntsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpp::AddThreeIntsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cpp::AddThreeIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b05623554ab950ed237d43d45f0b4dd";
  }

  static const char* value(const ::cpp::AddThreeIntsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b05623554ab950eULL;
  static const uint64_t static_value2 = 0xd237d43d45f0b4ddULL;
};

template<class ContainerAllocator>
struct DataType< ::cpp::AddThreeIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cpp/AddThreeIntsResponse";
  }

  static const char* value(const ::cpp::AddThreeIntsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cpp::AddThreeIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 result\n"
;
  }

  static const char* value(const ::cpp::AddThreeIntsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cpp::AddThreeIntsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddThreeIntsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cpp::AddThreeIntsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cpp::AddThreeIntsResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int64_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CPP_MESSAGE_ADDTHREEINTSRESPONSE_H
