// Generated by gencpp from file cpp/AddTwoInts.msg
// DO NOT EDIT!


#ifndef CPP_MESSAGE_ADDTWOINTS_H
#define CPP_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <cpp/AddTwoIntsRequest.h>
#include <cpp/AddTwoIntsResponse.h>


namespace cpp
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace cpp


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cpp::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::cpp::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::cpp::AddTwoInts > {
  static const char* value()
  {
    return "cpp/AddTwoInts";
  }

  static const char* value(const ::cpp::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::cpp::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::cpp::AddTwoInts >
template<>
struct MD5Sum< ::cpp::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cpp::AddTwoInts >::value();
  }
  static const char* value(const ::cpp::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cpp::AddTwoIntsRequest> should match
// service_traits::DataType< ::cpp::AddTwoInts >
template<>
struct DataType< ::cpp::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::cpp::AddTwoInts >::value();
  }
  static const char* value(const ::cpp::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cpp::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::cpp::AddTwoInts >
template<>
struct MD5Sum< ::cpp::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cpp::AddTwoInts >::value();
  }
  static const char* value(const ::cpp::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cpp::AddTwoIntsResponse> should match
// service_traits::DataType< ::cpp::AddTwoInts >
template<>
struct DataType< ::cpp::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::cpp::AddTwoInts >::value();
  }
  static const char* value(const ::cpp::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CPP_MESSAGE_ADDTWOINTS_H
