// Generated by gencpp from file cpp/LoopClosureFeedback.msg
// DO NOT EDIT!


#ifndef CPP_MESSAGE_LOOPCLOSUREFEEDBACK_H
#define CPP_MESSAGE_LOOPCLOSUREFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cpp
{
template <class ContainerAllocator>
struct LoopClosureFeedback_
{
  typedef LoopClosureFeedback_<ContainerAllocator> Type;

  LoopClosureFeedback_()
    : state(0)  {
    }
  LoopClosureFeedback_(const ContainerAllocator& _alloc)
    : state(0)  {
  (void)_alloc;
    }



   typedef int32_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::cpp::LoopClosureFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cpp::LoopClosureFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct LoopClosureFeedback_

typedef ::cpp::LoopClosureFeedback_<std::allocator<void> > LoopClosureFeedback;

typedef boost::shared_ptr< ::cpp::LoopClosureFeedback > LoopClosureFeedbackPtr;
typedef boost::shared_ptr< ::cpp::LoopClosureFeedback const> LoopClosureFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cpp::LoopClosureFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cpp::LoopClosureFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cpp::LoopClosureFeedback_<ContainerAllocator1> & lhs, const ::cpp::LoopClosureFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cpp::LoopClosureFeedback_<ContainerAllocator1> & lhs, const ::cpp::LoopClosureFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cpp

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cpp::LoopClosureFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cpp::LoopClosureFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cpp::LoopClosureFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cpp::LoopClosureFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpp::LoopClosureFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpp::LoopClosureFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cpp::LoopClosureFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7a2f37ef2ba405f0c7a15cc72663d6f0";
  }

  static const char* value(const ::cpp::LoopClosureFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7a2f37ef2ba405f0ULL;
  static const uint64_t static_value2 = 0xc7a15cc72663d6f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::cpp::LoopClosureFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cpp/LoopClosureFeedback";
  }

  static const char* value(const ::cpp::LoopClosureFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cpp::LoopClosureFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"int32 state\n"
;
  }

  static const char* value(const ::cpp::LoopClosureFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cpp::LoopClosureFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LoopClosureFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cpp::LoopClosureFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cpp::LoopClosureFeedback_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CPP_MESSAGE_LOOPCLOSUREFEEDBACK_H
