// Generated by gencpp from file cpp/RtabmapReprocessGoal.msg
// DO NOT EDIT!


#ifndef CPP_MESSAGE_RTABMAPREPROCESSGOAL_H
#define CPP_MESSAGE_RTABMAPREPROCESSGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cpp
{
template <class ContainerAllocator>
struct RtabmapReprocessGoal_
{
  typedef RtabmapReprocessGoal_<ContainerAllocator> Type;

  RtabmapReprocessGoal_()
    : databasepaths()
    , goal_path()  {
    }
  RtabmapReprocessGoal_(const ContainerAllocator& _alloc)
    : databasepaths(_alloc)
    , goal_path(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _databasepaths_type;
  _databasepaths_type databasepaths;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _goal_path_type;
  _goal_path_type goal_path;





  typedef boost::shared_ptr< ::cpp::RtabmapReprocessGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cpp::RtabmapReprocessGoal_<ContainerAllocator> const> ConstPtr;

}; // struct RtabmapReprocessGoal_

typedef ::cpp::RtabmapReprocessGoal_<std::allocator<void> > RtabmapReprocessGoal;

typedef boost::shared_ptr< ::cpp::RtabmapReprocessGoal > RtabmapReprocessGoalPtr;
typedef boost::shared_ptr< ::cpp::RtabmapReprocessGoal const> RtabmapReprocessGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cpp::RtabmapReprocessGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cpp::RtabmapReprocessGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cpp::RtabmapReprocessGoal_<ContainerAllocator1> & lhs, const ::cpp::RtabmapReprocessGoal_<ContainerAllocator2> & rhs)
{
  return lhs.databasepaths == rhs.databasepaths &&
    lhs.goal_path == rhs.goal_path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cpp::RtabmapReprocessGoal_<ContainerAllocator1> & lhs, const ::cpp::RtabmapReprocessGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cpp

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cpp::RtabmapReprocessGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cpp::RtabmapReprocessGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cpp::RtabmapReprocessGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cpp::RtabmapReprocessGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpp::RtabmapReprocessGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpp::RtabmapReprocessGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cpp::RtabmapReprocessGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e6b31abfb6499b91347d6e40d9d2808c";
  }

  static const char* value(const ::cpp::RtabmapReprocessGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe6b31abfb6499b91ULL;
  static const uint64_t static_value2 = 0x347d6e40d9d2808cULL;
};

template<class ContainerAllocator>
struct DataType< ::cpp::RtabmapReprocessGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cpp/RtabmapReprocessGoal";
  }

  static const char* value(const ::cpp::RtabmapReprocessGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cpp::RtabmapReprocessGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"string[] databasepaths\n"
"string goal_path\n"
;
  }

  static const char* value(const ::cpp::RtabmapReprocessGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cpp::RtabmapReprocessGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.databasepaths);
      stream.next(m.goal_path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RtabmapReprocessGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cpp::RtabmapReprocessGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cpp::RtabmapReprocessGoal_<ContainerAllocator>& v)
  {
    s << indent << "databasepaths[]" << std::endl;
    for (size_t i = 0; i < v.databasepaths.size(); ++i)
    {
      s << indent << "  databasepaths[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.databasepaths[i]);
    }
    s << indent << "goal_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.goal_path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CPP_MESSAGE_RTABMAPREPROCESSGOAL_H
