// Generated by gencpp from file cpp/RtabmapReprocessResult.msg
// DO NOT EDIT!


#ifndef CPP_MESSAGE_RTABMAPREPROCESSRESULT_H
#define CPP_MESSAGE_RTABMAPREPROCESSRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cpp
{
template <class ContainerAllocator>
struct RtabmapReprocessResult_
{
  typedef RtabmapReprocessResult_<ContainerAllocator> Type;

  RtabmapReprocessResult_()
    : result(0)  {
    }
  RtabmapReprocessResult_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int32_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::cpp::RtabmapReprocessResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cpp::RtabmapReprocessResult_<ContainerAllocator> const> ConstPtr;

}; // struct RtabmapReprocessResult_

typedef ::cpp::RtabmapReprocessResult_<std::allocator<void> > RtabmapReprocessResult;

typedef boost::shared_ptr< ::cpp::RtabmapReprocessResult > RtabmapReprocessResultPtr;
typedef boost::shared_ptr< ::cpp::RtabmapReprocessResult const> RtabmapReprocessResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cpp::RtabmapReprocessResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cpp::RtabmapReprocessResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cpp::RtabmapReprocessResult_<ContainerAllocator1> & lhs, const ::cpp::RtabmapReprocessResult_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cpp::RtabmapReprocessResult_<ContainerAllocator1> & lhs, const ::cpp::RtabmapReprocessResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cpp

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cpp::RtabmapReprocessResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cpp::RtabmapReprocessResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cpp::RtabmapReprocessResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cpp::RtabmapReprocessResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpp::RtabmapReprocessResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpp::RtabmapReprocessResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cpp::RtabmapReprocessResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const ::cpp::RtabmapReprocessResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x034a8e20d6a30666ULL;
  static const uint64_t static_value2 = 0x5e3a5b340fab3f09ULL;
};

template<class ContainerAllocator>
struct DataType< ::cpp::RtabmapReprocessResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cpp/RtabmapReprocessResult";
  }

  static const char* value(const ::cpp::RtabmapReprocessResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cpp::RtabmapReprocessResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"int32 result\n"
;
  }

  static const char* value(const ::cpp::RtabmapReprocessResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cpp::RtabmapReprocessResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RtabmapReprocessResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cpp::RtabmapReprocessResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cpp::RtabmapReprocessResult_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CPP_MESSAGE_RTABMAPREPROCESSRESULT_H
