// Generated by gencpp from file cpp/StringArray.msg
// DO NOT EDIT!


#ifndef CPP_MESSAGE_STRINGARRAY_H
#define CPP_MESSAGE_STRINGARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cpp
{
template <class ContainerAllocator>
struct StringArray_
{
  typedef StringArray_<ContainerAllocator> Type;

  StringArray_()
    : strings()  {
    }
  StringArray_(const ContainerAllocator& _alloc)
    : strings(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _strings_type;
  _strings_type strings;





  typedef boost::shared_ptr< ::cpp::StringArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cpp::StringArray_<ContainerAllocator> const> ConstPtr;

}; // struct StringArray_

typedef ::cpp::StringArray_<std::allocator<void> > StringArray;

typedef boost::shared_ptr< ::cpp::StringArray > StringArrayPtr;
typedef boost::shared_ptr< ::cpp::StringArray const> StringArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cpp::StringArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cpp::StringArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cpp::StringArray_<ContainerAllocator1> & lhs, const ::cpp::StringArray_<ContainerAllocator2> & rhs)
{
  return lhs.strings == rhs.strings;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cpp::StringArray_<ContainerAllocator1> & lhs, const ::cpp::StringArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cpp

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cpp::StringArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cpp::StringArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cpp::StringArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cpp::StringArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpp::StringArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpp::StringArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cpp::StringArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "51789d20146e565223d0963361aecda1";
  }

  static const char* value(const ::cpp::StringArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x51789d20146e5652ULL;
  static const uint64_t static_value2 = 0x23d0963361aecda1ULL;
};

template<class ContainerAllocator>
struct DataType< ::cpp::StringArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cpp/StringArray";
  }

  static const char* value(const ::cpp::StringArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cpp::StringArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] strings\n"
;
  }

  static const char* value(const ::cpp::StringArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cpp::StringArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.strings);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StringArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cpp::StringArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cpp::StringArray_<ContainerAllocator>& v)
  {
    s << indent << "strings[]" << std::endl;
    for (size_t i = 0; i < v.strings.size(); ++i)
    {
      s << indent << "  strings[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.strings[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CPP_MESSAGE_STRINGARRAY_H
