(cl:defpackage ros_service_assignment-srv
  (:use )
  (:export
   "RECTANGLEAREASERVICE"
   "<RECTANGLEAREASERVICE-REQUEST>"
   "RECTANGLEAREASERVICE-REQUEST"
   "<RECTANGLEAREASERVICE-RESPONSE>"
   "RECTANGLEAREASERVICE-RESPONSE"
  ))

