// Generated by gencpp from file T/RectangleAreaService.msg
// DO NOT EDIT!


#ifndef T_MESSAGE_RECTANGLEAREASERVICE_H
#define T_MESSAGE_RECTANGLEAREASERVICE_H

#include <ros/service_traits.h>


#include <T/RectangleAreaServiceRequest.h>
#include <T/RectangleAreaServiceResponse.h>


namespace T
{

struct RectangleAreaService
{

typedef RectangleAreaServiceRequest Request;
typedef RectangleAreaServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RectangleAreaService
} // namespace T


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::T::RectangleAreaService > {
  static const char* value()
  {
    return "9d875babe5658f30073750c15b75fb29";
  }

  static const char* value(const ::T::RectangleAreaService&) { return value(); }
};

template<>
struct DataType< ::T::RectangleAreaService > {
  static const char* value()
  {
    return "T/RectangleAreaService";
  }

  static const char* value(const ::T::RectangleAreaService&) { return value(); }
};


// service_traits::MD5Sum< ::T::RectangleAreaServiceRequest> should match
// service_traits::MD5Sum< ::T::RectangleAreaService >
template<>
struct MD5Sum< ::T::RectangleAreaServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::T::RectangleAreaService >::value();
  }
  static const char* value(const ::T::RectangleAreaServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::T::RectangleAreaServiceRequest> should match
// service_traits::DataType< ::T::RectangleAreaService >
template<>
struct DataType< ::T::RectangleAreaServiceRequest>
{
  static const char* value()
  {
    return DataType< ::T::RectangleAreaService >::value();
  }
  static const char* value(const ::T::RectangleAreaServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::T::RectangleAreaServiceResponse> should match
// service_traits::MD5Sum< ::T::RectangleAreaService >
template<>
struct MD5Sum< ::T::RectangleAreaServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::T::RectangleAreaService >::value();
  }
  static const char* value(const ::T::RectangleAreaServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::T::RectangleAreaServiceResponse> should match
// service_traits::DataType< ::T::RectangleAreaService >
template<>
struct DataType< ::T::RectangleAreaServiceResponse>
{
  static const char* value()
  {
    return DataType< ::T::RectangleAreaService >::value();
  }
  static const char* value(const ::T::RectangleAreaServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // T_MESSAGE_RECTANGLEAREASERVICE_H
