axis_linear: 7
axis_angular: 6

scale_linear: 0.5
scale_linear_turbo: 1.0

scale_angular: 0.1
scale_angular_turbo: 0.3

enable_button: 0  
enable_turbo_button: 1  




# 10 = enable_turbo_button L3 (left joystick press)
# 1 = axis_linear left joystick vertical
# 0 = axis_angular left joystick horizontal
# 7 = axis_linear vertical arrow
# 6 = axis_angular horizontal arrow
# 1 = enable_turbo_button blue cross button
# 0 = enable_button pink square button
