// Generated by gencpp from file service_practice/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SERVICE_PRACTICE_MESSAGE_ADDTWOINTS_H
#define SERVICE_PRACTICE_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <service_practice/AddTwoIntsRequest.h>
#include <service_practice/AddTwoIntsResponse.h>


namespace service_practice
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace service_practice


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::service_practice::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::service_practice::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::service_practice::AddTwoInts > {
  static const char* value()
  {
    return "service_practice/AddTwoInts";
  }

  static const char* value(const ::service_practice::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::service_practice::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::service_practice::AddTwoInts >
template<>
struct MD5Sum< ::service_practice::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::service_practice::AddTwoInts >::value();
  }
  static const char* value(const ::service_practice::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_practice::AddTwoIntsRequest> should match
// service_traits::DataType< ::service_practice::AddTwoInts >
template<>
struct DataType< ::service_practice::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::service_practice::AddTwoInts >::value();
  }
  static const char* value(const ::service_practice::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::service_practice::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::service_practice::AddTwoInts >
template<>
struct MD5Sum< ::service_practice::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::service_practice::AddTwoInts >::value();
  }
  static const char* value(const ::service_practice::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_practice::AddTwoIntsResponse> should match
// service_traits::DataType< ::service_practice::AddTwoInts >
template<>
struct DataType< ::service_practice::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::service_practice::AddTwoInts >::value();
  }
  static const char* value(const ::service_practice::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICE_PRACTICE_MESSAGE_ADDTWOINTS_H
