// Generated by gencpp from file new_ros/AddTwoPoints.msg
// DO NOT EDIT!


#ifndef NEW_ROS_MESSAGE_ADDTWOPOINTS_H
#define NEW_ROS_MESSAGE_ADDTWOPOINTS_H

#include <ros/service_traits.h>


#include <new_ros/AddTwoPointsRequest.h>
#include <new_ros/AddTwoPointsResponse.h>


namespace new_ros
{

struct AddTwoPoints
{

typedef AddTwoPointsRequest Request;
typedef AddTwoPointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoPoints
} // namespace new_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::new_ros::AddTwoPoints > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::new_ros::AddTwoPoints&) { return value(); }
};

template<>
struct DataType< ::new_ros::AddTwoPoints > {
  static const char* value()
  {
    return "new_ros/AddTwoPoints";
  }

  static const char* value(const ::new_ros::AddTwoPoints&) { return value(); }
};


// service_traits::MD5Sum< ::new_ros::AddTwoPointsRequest> should match
// service_traits::MD5Sum< ::new_ros::AddTwoPoints >
template<>
struct MD5Sum< ::new_ros::AddTwoPointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::new_ros::AddTwoPoints >::value();
  }
  static const char* value(const ::new_ros::AddTwoPointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::new_ros::AddTwoPointsRequest> should match
// service_traits::DataType< ::new_ros::AddTwoPoints >
template<>
struct DataType< ::new_ros::AddTwoPointsRequest>
{
  static const char* value()
  {
    return DataType< ::new_ros::AddTwoPoints >::value();
  }
  static const char* value(const ::new_ros::AddTwoPointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::new_ros::AddTwoPointsResponse> should match
// service_traits::MD5Sum< ::new_ros::AddTwoPoints >
template<>
struct MD5Sum< ::new_ros::AddTwoPointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::new_ros::AddTwoPoints >::value();
  }
  static const char* value(const ::new_ros::AddTwoPointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::new_ros::AddTwoPointsResponse> should match
// service_traits::DataType< ::new_ros::AddTwoPoints >
template<>
struct DataType< ::new_ros::AddTwoPointsResponse>
{
  static const char* value()
  {
    return DataType< ::new_ros::AddTwoPoints >::value();
  }
  static const char* value(const ::new_ros::AddTwoPointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NEW_ROS_MESSAGE_ADDTWOPOINTS_H
