; Auto-generated. Do not edit!


(cl:in-package cpp-msg)


;//! \htmlinclude LoopClosureGoal.msg.html

(cl:defclass <LoopClosureGoal> (roslisp-msg-protocol:ros-message)
  ((imagepath
    :reader imagepath
    :initarg :imagepath
    :type cl:string
    :initform ""))
)

(cl:defclass LoopClosureGoal (<LoopClosureGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LoopClosureGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LoopClosureGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cpp-msg:<LoopClosureGoal> is deprecated: use cpp-msg:LoopClosureGoal instead.")))

(cl:ensure-generic-function 'imagepath-val :lambda-list '(m))
(cl:defmethod imagepath-val ((m <LoopClosureGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cpp-msg:imagepath-val is deprecated.  Use cpp-msg:imagepath instead.")
  (imagepath m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LoopClosureGoal>) ostream)
  "Serializes a message object of type '<LoopClosureGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'imagepath))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'imagepath))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LoopClosureGoal>) istream)
  "Deserializes a message object of type '<LoopClosureGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'imagepath) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'imagepath) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LoopClosureGoal>)))
  "Returns string type for a message object of type '<LoopClosureGoal>"
  "cpp/LoopClosureGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LoopClosureGoal)))
  "Returns string type for a message object of type 'LoopClosureGoal"
  "cpp/LoopClosureGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LoopClosureGoal>)))
  "Returns md5sum for a message object of type '<LoopClosureGoal>"
  "bc491c80e6e5522eb310dc6a0d6adc73")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LoopClosureGoal)))
  "Returns md5sum for a message object of type 'LoopClosureGoal"
  "bc491c80e6e5522eb310dc6a0d6adc73")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LoopClosureGoal>)))
  "Returns full string definition for message of type '<LoopClosureGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%string imagepath~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LoopClosureGoal)))
  "Returns full string definition for message of type 'LoopClosureGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%string imagepath~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LoopClosureGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'imagepath))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LoopClosureGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'LoopClosureGoal
    (cl:cons ':imagepath (imagepath msg))
))
