; Auto-generated. Do not edit!


(cl:in-package cpp-msg)


;//! \htmlinclude LoopClosureResult.msg.html

(cl:defclass <LoopClosureResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass LoopClosureResult (<LoopClosureResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LoopClosureResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LoopClosureResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cpp-msg:<LoopClosureResult> is deprecated: use cpp-msg:LoopClosureResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <LoopClosureResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cpp-msg:result-val is deprecated.  Use cpp-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LoopClosureResult>) ostream)
  "Serializes a message object of type '<LoopClosureResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'result) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LoopClosureResult>) istream)
  "Deserializes a message object of type '<LoopClosureResult>"
    (cl:setf (cl:slot-value msg 'result) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LoopClosureResult>)))
  "Returns string type for a message object of type '<LoopClosureResult>"
  "cpp/LoopClosureResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LoopClosureResult)))
  "Returns string type for a message object of type 'LoopClosureResult"
  "cpp/LoopClosureResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LoopClosureResult>)))
  "Returns md5sum for a message object of type '<LoopClosureResult>"
  "eb13ac1f1354ccecb7941ee8fa2192e8")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LoopClosureResult)))
  "Returns md5sum for a message object of type 'LoopClosureResult"
  "eb13ac1f1354ccecb7941ee8fa2192e8")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LoopClosureResult>)))
  "Returns full string definition for message of type '<LoopClosureResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LoopClosureResult)))
  "Returns full string definition for message of type 'LoopClosureResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LoopClosureResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LoopClosureResult>))
  "Converts a ROS message object to a list"
  (cl:list 'LoopClosureResult
    (cl:cons ':result (result msg))
))
