// Generated by gencpp from file new_ros/AddTwoPointsRequest.msg
// DO NOT EDIT!


#ifndef NEW_ROS_MESSAGE_ADDTWOPOINTSREQUEST_H
#define NEW_ROS_MESSAGE_ADDTWOPOINTSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace new_ros
{
template <class ContainerAllocator>
struct AddTwoPointsRequest_
{
  typedef AddTwoPointsRequest_<ContainerAllocator> Type;

  AddTwoPointsRequest_()
    : a(0)
    , b(0)  {
    }
  AddTwoPointsRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;

   typedef int64_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::new_ros::AddTwoPointsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::new_ros::AddTwoPointsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddTwoPointsRequest_

typedef ::new_ros::AddTwoPointsRequest_<std::allocator<void> > AddTwoPointsRequest;

typedef boost::shared_ptr< ::new_ros::AddTwoPointsRequest > AddTwoPointsRequestPtr;
typedef boost::shared_ptr< ::new_ros::AddTwoPointsRequest const> AddTwoPointsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::new_ros::AddTwoPointsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::new_ros::AddTwoPointsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::new_ros::AddTwoPointsRequest_<ContainerAllocator1> & lhs, const ::new_ros::AddTwoPointsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::new_ros::AddTwoPointsRequest_<ContainerAllocator1> & lhs, const ::new_ros::AddTwoPointsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace new_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::new_ros::AddTwoPointsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::new_ros::AddTwoPointsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::new_ros::AddTwoPointsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::new_ros::AddTwoPointsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::new_ros::AddTwoPointsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::new_ros::AddTwoPointsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::new_ros::AddTwoPointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36d09b846be0b371c5f190354dd3153e";
  }

  static const char* value(const ::new_ros::AddTwoPointsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36d09b846be0b371ULL;
  static const uint64_t static_value2 = 0xc5f190354dd3153eULL;
};

template<class ContainerAllocator>
struct DataType< ::new_ros::AddTwoPointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "new_ros/AddTwoPointsRequest";
  }

  static const char* value(const ::new_ros::AddTwoPointsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::new_ros::AddTwoPointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 a\n"
"int64 b\n"
;
  }

  static const char* value(const ::new_ros::AddTwoPointsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::new_ros::AddTwoPointsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddTwoPointsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::new_ros::AddTwoPointsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::new_ros::AddTwoPointsRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int64_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEW_ROS_MESSAGE_ADDTWOPOINTSREQUEST_H
