(cl:defpackage cpp-srv
  (:use )
  (:export
   "ADDTHREEINTS"
   "<ADDTHREEINTS-REQUEST>"
   "ADDTHREEINTS-REQUEST"
   "<ADDTHREEINTS-RESPONSE>"
   "ADDTHREEINTS-RESPONSE"
   "SRVDEMO"
   "<SRVDEMO-REQUEST>"
   "SRVDEMO-REQUEST"
   "<SRVDEMO-RESPONSE>"
   "SRVDEMO-RESPONSE"
  ))

